In [10]:
import numpy as np 

#1
friend_1=np.array([1200,2300,10000,5000,6000,2300,3400])
friend_2=np.array([5000,2000,23500,8000,7000,4500,1200])

print("Addition:",np.add(friend_1,friend_2))
print("Subtraction:",np.subtract(friend_1,friend_2))
print("Multiplication:",np.multiply(friend_1,friend_2))
print("Division:",np.divide(friend_1,friend_2))

#2
user_prefrences=np.array([[23,12,34],
                          [23,12,34],
                          [23,54,34]])

song_popularity=np.array([[3,2,5],
                          [4,5,1],
                          [2,3,5]])

print("User_prefrence:\n",user_prefrences)
print("song popularity:\n",song_popularity)

print("Dot Product:\n",np.dot(user_prefrences,song_popularity))
print("Matrix Multiplication:\n",np.matmul(user_prefrences,song_popularity))

#For 2D matrices, np.dot() and np.matmul() give the same result;
#the difference is only in how they handle higher-dimensional arrays.

#3
matrix=np.arange(1,17).reshape(4,4)
print(matrix)
transposed_matrix=matrix.T
print("Transposed Matrix:\n",transposed_matrix)
print("Mean:",np.mean(transposed_matrix))
print("Median:",np.median(transposed_matrix))
print("Standard Deviation :",np.std(transposed_matrix))
print("Variance :",np.var(transposed_matrix))

#4
matrix=np.array([[1,2,3],
                 [0,1,4],
                 [5,6,0]])
print("Original Matrix:\n",matrix)
print("Inverse of Matrix:\n",np.linalg.inv(matrix))
print("Determinant of Matrix:",np.linalg.det(matrix))
print("Eigenvalues and Eigenvectors of Matrix:\n",np.linalg.eig(matrix))

#5
arr=np.array([[120,500,234,222,122,223],
              [450,340,120,340,510,230]])
print(arr)
print("Reshaped array:\n",arr.reshape(3,4))
flattened_array=arr.flatten()
print("Flatten:",flattened_array)
parts=np.split(flattened_array,2)
print("Splitted array:",parts)
print("Vertical Stacking:",np.vstack(parts))

Addition: [ 6200  4300 33500 13000 13000  6800  4600]
Subtraction: [ -3800    300 -13500  -3000  -1000  -2200   2200]
Multiplication: [  6000000   4600000 235000000  40000000  42000000  10350000   4080000]
Division: [0.24       1.15       0.42553191 0.625      0.85714286 0.51111111
 2.83333333]
User_prefrence:
 [[23 12 34]
 [23 12 34]
 [23 54 34]]
song popularity:
 [[3 2 5]
 [4 5 1]
 [2 3 5]]
Dot Product:
 [[185 208 297]
 [185 208 297]
 [353 418 339]]
Matrix Multiplication:
 [[185 208 297]
 [185 208 297]
 [353 418 339]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transposed Matrix:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Mean: 8.5
Median: 8.5
Standard Deviation : 4.6097722286464435
Variance : 21.25
Original Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse of Matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
Determinant of Matrix: 0.9999999999999964
Eigenvalues and Eigenvectors of Matrix:
 EigResult(eigenvalues=array([-5.2296696 , -0.0263