In [ ]:
import numpy as np 

followers=np.array([1200,15000,67000,340000,1250000])
print(followers)
print("Shape of followers:",followers.shape)
print("Number of dimensions of followers  :",followers.ndim)
print("Data Type of followers :",followers.dtype)


order_ids=np.arange(101,111)
print(order_ids)
print("Size of Order_ids :",order_ids.size)

like=np.eye(3,3)
print("Matrix:\n",like)
#Diagonal (1) represents that each playlist item matched with itself
#Diagonal (0) represents no match between different playlist 

Scores=[45,67,120,89,54]
array_scores=np.array(Scores)
print(array_scores)
print("Byte size:",array_scores.itemsize)

[   1200   15000   67000  340000 1250000]
Shape of followers: (5,)
Number of dimensions of followers  : 1
Data Type of followers : int64
[101 102 103 104 105 106 107 108 109 110]
Size of Order_ids : 10
Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 45  67 120  89  54]
Bytes size: 8
